export const COMMANDS = {
    add: 'add',
    rm: 'rm',
    rn: 'rn',
    cat: 'cat',  
    cp: 'cp',
    mv: 'mv',
    ls: 'ls',
    up: 'up',
    cd: 'cd',
    hash: 'hash',
    os: 'os',
    compress: 'compress',
    decompress: 'decompress',
  }